package com.bsat_dummy.bsatnewen;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Module implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String reward_or_bonus;
	private int wcs_product;

	private int qualified_dealers;

	private int qualified_TSI;

	public Module() {
	}

	public java.lang.String getReward_or_bonus() {
		return this.reward_or_bonus;
	}

	public void setReward_or_bonus(java.lang.String reward_or_bonus) {
		this.reward_or_bonus = reward_or_bonus;
	}

	public int getWcs_product() {
		return this.wcs_product;
	}

	public void setWcs_product(int wcs_product) {
		this.wcs_product = wcs_product;
	}

	public int getQualified_dealers() {
		return this.qualified_dealers;
	}

	public void setQualified_dealers(int qualified_dealers) {
		this.qualified_dealers = qualified_dealers;
	}

	public int getQualified_TSI() {
		return this.qualified_TSI;
	}

	public void setQualified_TSI(int qualified_TSI) {
		this.qualified_TSI = qualified_TSI;
	}

	public Module(java.lang.String reward_or_bonus, int wcs_product,
			int qualified_dealers, int qualified_TSI) {
		this.reward_or_bonus = reward_or_bonus;
		this.wcs_product = wcs_product;
		this.qualified_dealers = qualified_dealers;
		this.qualified_TSI = qualified_TSI;
	}

}